"use client"

import { useActionState } from "react"
import { setPublicProjectAction, updatePreferencesAction, type GrowthActionState } from "@/app/(user)/growth-actions"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import type { GrowthProject, UserPreferences } from "@/lib/growth/types"

export function PreferencesForm({ preferences }: { preferences: UserPreferences }) {
  const [state, action, pending] = useActionState(updatePreferencesAction, {} as GrowthActionState)
  return <form action={action} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Conversation style"><select name="coachTone" defaultValue={preferences.coachTone} className="h-10 w-full rounded-xl border border-neutral-200 bg-white px-3 text-sm"><option value="supportive">Supportive</option><option value="balanced">Balanced</option><option value="blunt">Direct</option></select></Field><Field label="Reflection rhythm"><select name="checkInCadence" defaultValue={preferences.checkInCadence} className="h-10 w-full rounded-xl border border-neutral-200 bg-white px-3 text-sm"><option value="daily">Daily</option><option value="every_other_day">Every other day</option></select></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Hour"><Input name="checkInHour" type="number" min={0} max={23} defaultValue={preferences.checkInHour} /></Field><Field label="Minute"><Input name="checkInMinute" type="number" min={0} max={59} defaultValue={preferences.checkInMinute} /></Field><Field label="Timezone"><Input name="timezone" defaultValue={preferences.timezone} /></Field></div><input type="hidden" name="weeklyReviewDay" value={preferences.weeklyReviewDay} /><label className="flex gap-3 text-sm font-medium text-neutral-600"><input name="emailNotifications" type="checkbox" defaultChecked={preferences.emailNotifications} className="accent-neutral-950" />Gentle email reflection prompts</label>{state.error ? <p className="text-sm text-red-600">{state.error}</p> : null}{state.success ? <p className="text-sm text-emerald-700">{state.success}</p> : null}<Button disabled={pending} className="rounded-full bg-neutral-950 text-white hover:bg-neutral-800">{pending ? "Saving…" : "Save preferences"}</Button></form>
}

export function PublicProjectForm({ project }: { project: GrowthProject }) {
  const [state, action, pending] = useActionState(setPublicProjectAction, {} as GrowthActionState)
  return <form action={action} className="space-y-4"><input type="hidden" name="projectId" value={project.id} /><label className="flex gap-3 text-sm font-medium text-neutral-600"><input name="isPublic" type="checkbox" defaultChecked={project.isPublic} className="accent-neutral-950" />Publish a limited growth page</label><Field label="Public URL"><div className="flex items-center gap-2"><span className="text-sm text-neutral-400">/p/</span><Input name="publicSlug" defaultValue={project.publicSlug ?? ""} placeholder="my-gentle-reset" /></div></Field><label className="flex gap-3 text-sm font-medium text-neutral-600"><input name="showPublicStreak" type="checkbox" defaultChecked={project.showPublicStreak} className="accent-neutral-950" />Show reflection rhythm publicly</label><p className="text-xs leading-5 text-neutral-400">Your raw reflections, private reason, email, and inferred patterns are never shown.</p>{state.error ? <p className="text-sm text-red-600">{state.error}</p> : null}{state.success ? <p className="text-sm text-emerald-700">{state.success}</p> : null}<Button disabled={pending} variant="outline" className="rounded-full border-neutral-200">{pending ? "Updating…" : "Update public page"}</Button></form>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label className="font-bold text-neutral-800">{label}</Label>{children}</div> }
