import Link from "next/link"
import { AlertTriangle, CreditCard, Gift } from "lucide-react"

import { AdminBillingReplayForm } from "@/components/admin/admin-forms"
import { AdminPagination } from "@/components/admin/admin-pagination"
import { requireAdminPageRole } from "@/lib/admin/page-auth"
import { getAdminBilling } from "@/lib/data/admin"

export const metadata = { title: "Billing" }

function pageNumber(value?: string) { const page = Number(value); return Number.isInteger(page) && page > 0 ? page : 1 }
function date(value?: string) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—" }
function money(amount: number, currency: string) { return (amount / 100).toLocaleString("en-IN", { style: "currency", currency }) }

export default async function AdminBillingPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  await requireAdminPageRole("billing")
  const params = await searchParams
  const data = await getAdminBilling(pageNumber(params.page))
  const active = data.subscriptions.filter((item) => ["active", "authenticated", "charged"].includes(item.status)).length
  const openAlerts = data.alerts.filter((item) => item.status === "open")
  return <div className="space-y-7">
    <section><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Revenue operations</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Billing</h1><p className="mt-2 text-sm text-neutral-500">Provider-owned subscriptions, durable webhook processing, reconciliation, and audited complimentary access.</p></section>
    <section className="grid gap-3 sm:grid-cols-4"><Metric label="Subscriptions" value={data.subscriptions.length} icon={CreditCard} /><Metric label="Active" value={active} icon={CreditCard} /><Metric label="Open alerts" value={openAlerts.length} icon={AlertTriangle} /><Metric label="Complimentary grants" value={data.grants.length} icon={Gift} /></section>
    {openAlerts.length ? <Section title="Open billing alerts" description="Investigate critical drift and repeated webhook failures before selling new subscriptions."><div className="space-y-2">{openAlerts.map((alert) => <article key={alert.id} className="flex gap-3 rounded-xl border border-amber-400/15 bg-amber-400/5 p-3"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-300" /><div><p className="text-xs font-semibold text-neutral-200">{alert.kind.replaceAll("_", " ")} · {alert.severity}</p><p className="mt-1 text-xs leading-5 text-neutral-500">{alert.message}</p><p className="mt-1 text-[9px] text-neutral-700">Updated {date(alert.updatedAt)}</p></div></article>)}</div></Section> : null}
    <Section title="Subscriptions" description="Locally recorded provider subscriptions; checkout redirects never grant access."><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-white/8 text-[10px] uppercase tracking-wider text-neutral-600"><th className="pb-3">User</th><th className="pb-3">Provider ID</th><th className="pb-3">Plan</th><th className="pb-3">Amount</th><th className="pb-3">State</th><th className="pb-3 text-right">Updated</th></tr></thead><tbody>{data.subscriptions.map((item) => <tr key={item.id} className="border-b border-white/5 last:border-0"><td className="py-3"><Link href={`/admin/users/${item.userId}`} className="text-xs font-semibold text-neutral-300 hover:text-primary">{item.user?.name ?? "Deleted user"}<span className="block text-[9px] text-neutral-700">{item.user?.email}</span></Link></td><td className="max-w-52 truncate py-3 font-mono text-[9px] text-neutral-600">{item.providerSubscriptionId}</td><td className="py-3 text-xs capitalize text-neutral-400">{item.planTier}</td><td className="py-3 text-xs text-neutral-400">{money(item.amount, item.currency)}</td><td className="py-3"><Status value={item.status} /></td><td className="py-3 text-right text-[9px] text-neutral-700">{date(item.updatedAt)}</td></tr>)}</tbody></table>{!data.subscriptions.length ? <Empty>No subscriptions have been recorded.</Empty> : null}</div></Section>
    <Section title="Webhook events" description="Receipts remain visible even when downstream processing fails. Owner MFA is required to replay."><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead><tr className="border-b border-white/8 text-[10px] uppercase tracking-wider text-neutral-600"><th className="pb-3">Event</th><th className="pb-3">Provider ID</th><th className="pb-3">Status</th><th className="pb-3">Attempts</th><th className="pb-3">Disposition / failure</th><th className="pb-3">Retry</th><th className="pb-3">Action</th><th className="pb-3 text-right">Received</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.id} className="border-b border-white/5 align-top last:border-0"><td className="py-3 text-xs font-semibold text-neutral-300">{event.eventType}</td><td className="max-w-44 truncate py-3 font-mono text-[9px] text-neutral-600">{event.providerEventId}</td><td className="py-3"><Status value={event.status} /></td><td className="py-3 text-xs text-neutral-500">{event.attemptCount ?? 0}</td><td className="max-w-64 py-3 text-[10px] text-neutral-500">{event.finalDisposition ?? event.failureCategory ?? "pending"}{event.failureReason ? <span className="block text-red-300/70">{event.failureReason}</span> : null}</td><td className="py-3 text-[9px] text-neutral-600">{date(event.nextRetryAt)}</td><td className="py-2">{["failed", "dead_letter"].includes(event.status) ? <AdminBillingReplayForm providerEventId={event.providerEventId} /> : "—"}</td><td className="py-3 text-right text-[9px] text-neutral-700">{date(event.createdAt)}</td></tr>)}</tbody></table></div><AdminPagination page={data.page} pages={data.pages} basePath="/admin/billing" /></Section>
    <Section title="Complimentary access" description="Separate from paid subscriptions and limited to one year per grant."><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-white/8 text-[10px] uppercase tracking-wider text-neutral-600"><th className="pb-3">User</th><th className="pb-3">Plan</th><th className="pb-3">Source</th><th className="pb-3">Reason</th><th className="pb-3">Window</th></tr></thead><tbody>{data.grants.map((grant) => <tr key={grant.id} className="border-b border-white/5 last:border-0"><td className="py-3 text-xs text-neutral-300">{grant.user?.email ?? grant.userId}</td><td className="py-3 text-xs capitalize text-neutral-400">{grant.planTier}</td><td className="py-3 text-xs text-neutral-500">{grant.source.replaceAll("_", " ")}</td><td className="max-w-72 py-3 text-xs text-neutral-500">{grant.reason}</td><td className="py-3 text-[9px] text-neutral-600">{date(grant.startsAt)} → {date(grant.expiresAt)}</td></tr>)}</tbody></table>{!data.grants.length ? <Empty>No complimentary grants.</Empty> : null}</div></Section>
  </div>
}

function Section({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:p-6"><h2 className="text-sm font-bold text-white">{title}</h2><p className="mb-5 mt-1 text-xs text-neutral-600">{description}</p>{children}</section> }
function Empty({ children }: { children: React.ReactNode }) { return <p className="py-12 text-center text-xs text-neutral-600">{children}</p> }
function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof CreditCard }) { return <article className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><Icon className="size-4 text-primary" /><p className="mt-5 text-2xl font-black text-white">{value}</p><p className="mt-1 text-[10px] text-neutral-600">{label}</p></article> }
function Status({ value }: { value: string }) { const bad = ["failed", "dead_letter", "cancelled", "refunded"].includes(value); return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${bad ? "bg-red-500/10 text-red-300" : "bg-emerald-500/10 text-emerald-400"}`}>{value}</span> }
