import Link from "next/link"
import { CreditCard, ReceiptText } from "lucide-react"

import { AdminPagination } from "@/components/admin/admin-pagination"
import { getAdminBilling } from "@/lib/data/admin"
import { requireAdminPageRole } from "@/lib/admin/page-auth"

export const metadata = { title: "Billing" }

function pageNumber(value?: string) { const page = Number(value); return Number.isInteger(page) && page > 0 ? page : 1 }
function date(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) }
function money(amount: number, currency: string) { return (amount / 100).toLocaleString("en-IN", { style: "currency", currency }) }

export default async function AdminBillingPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  await requireAdminPageRole("billing")
  const params = await searchParams
  const data = await getAdminBilling(pageNumber(params.page))
  const active = data.subscriptions.filter((item) => ["active", "authenticated", "charged"].includes(item.status)).length
  return <div className="space-y-7"><section><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Revenue operations</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Billing</h1><p className="mt-2 text-sm text-neutral-500">Razorpay subscriptions and webhook processing health. Provider state remains webhook-owned.</p></section><section className="grid gap-3 sm:grid-cols-3"><Metric label="Subscriptions" value={data.subscriptions.length} icon={CreditCard} /><Metric label="Active" value={active} icon={CreditCard} /><Metric label="Billing events" value={data.totalEvents} icon={ReceiptText} /></section>
  <section className="rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:p-6"><h2 className="text-sm font-bold text-white">Subscriptions</h2><p className="mt-1 text-xs text-neutral-600">Current locally recorded provider subscriptions</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-white/8 text-[10px] uppercase tracking-wider text-neutral-600"><th className="pb-3">User</th><th className="pb-3">Provider ID</th><th className="pb-3">Plan</th><th className="pb-3">Amount</th><th className="pb-3">Status</th><th className="pb-3 text-right">Updated</th></tr></thead><tbody>{data.subscriptions.map((item) => <tr key={item.id} className="border-b border-white/5 last:border-0"><td className="py-3"><Link href={`/admin/users/${item.userId}`} className="text-xs font-semibold text-neutral-300 hover:text-primary">{item.user?.name ?? "Deleted user"}<span className="block text-[9px] text-neutral-700">{item.user?.email}</span></Link></td><td className="max-w-52 truncate py-3 font-mono text-[9px] text-neutral-600">{item.providerSubscriptionId}</td><td className="py-3 text-xs capitalize text-neutral-400">{item.planTier}</td><td className="py-3 text-xs text-neutral-400">{money(item.amount, item.currency)}</td><td className="py-3"><Status value={item.status} /></td><td className="py-3 text-right text-[9px] text-neutral-700">{date(item.updatedAt)}</td></tr>)}</tbody></table>{!data.subscriptions.length ? <p className="py-12 text-center text-xs text-neutral-600">No subscriptions have been recorded.</p> : null}</div></section>
  <section className="rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:p-6"><h2 className="text-sm font-bold text-white">Webhook events</h2><p className="mt-1 text-xs text-neutral-600">Immutable billing event processing history</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-white/8 text-[10px] uppercase tracking-wider text-neutral-600"><th className="pb-3">Event</th><th className="pb-3">Provider ID</th><th className="pb-3">Status</th><th className="pb-3">Failure</th><th className="pb-3 text-right">Received</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.id} className="border-b border-white/5 last:border-0"><td className="py-3 text-xs font-semibold text-neutral-300">{event.eventType}</td><td className="max-w-52 truncate py-3 font-mono text-[9px] text-neutral-600">{event.providerEventId}</td><td className="py-3"><Status value={event.status} /></td><td className="max-w-64 truncate py-3 text-[9px] text-red-300/70">{event.failureReason ?? "—"}</td><td className="py-3 text-right text-[9px] text-neutral-700">{date(event.createdAt)}</td></tr>)}</tbody></table></div><AdminPagination page={data.page} pages={data.pages} basePath="/admin/billing" /></section></div>
}

function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof CreditCard }) { return <article className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><Icon className="size-4 text-primary" /><p className="mt-5 text-2xl font-black text-white">{value}</p><p className="mt-1 text-[10px] text-neutral-600">{label}</p></article> }
function Status({ value }: { value: string }) { const bad = value === "failed" || value === "cancelled"; return <span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${bad ? "bg-red-500/10 text-red-300" : "bg-emerald-500/10 text-emerald-400"}`}>{value}</span> }
