import Link from "next/link"
import { Bug, CreditCard, Lightbulb, Mail, ShieldAlert } from "lucide-react"
import { SiteFooter } from "@/components/landing/site-footer"
import { legalDetails } from "@/lib/legal"

export const metadata = { title: "Contact and feedback", description: "Contact GrowthAI support, report a bug, or share product feedback." }
export default function ContactPage() {
  const legal = legalDetails()
  return <main className="min-h-screen bg-[#fafafa] text-neutral-950"><section className="mx-auto max-w-5xl px-5 py-20 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Contact and feedback</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-6xl">Talk to a real person.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-neutral-500">Use the category that best matches your request. Do not email passwords, payment-card details, crisis information, or sensitive conversation text.</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><Contact icon={Lightbulb} title="Product feedback" email={legal.supportContact} subject="GrowthAI product feedback" text="Tell us what happened, what you expected, and what would have been more useful." /><Contact icon={Bug} title="Beta bug" email={legal.supportContact} subject="GrowthAI beta bug" text="Include the route, approximate time, browser, and reproducible steps—without private chat content." /><Contact icon={CreditCard} title="Billing support" email={legal.supportContact} subject="GrowthAI billing support" text="Include your account email and the last four characters of the subscription ID, never payment credentials." /><Contact icon={ShieldAlert} title="Security report" email={legal.securityContact} subject="GrowthAI security report" text="Send suspected vulnerabilities to the monitored security address. Avoid accessing anyone else’s data." /></div><p className="mt-8 text-sm text-neutral-500">Public-beta target: a reply within three business days. Read our <Link href="/privacy" className="underline">Privacy Notice</Link> and <Link href="/security" className="underline">Security practices</Link>.</p></section><SiteFooter /></main>
}
function Contact({ icon: Icon, title, email, subject, text }: { icon: typeof Mail; title: string; email: string; subject: string; text: string }) { return <article className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm"><Icon className="size-5 text-primary" /><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-neutral-500">{text}</p><a href={`mailto:${email}?subject=${encodeURIComponent(subject)}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-neutral-900 underline underline-offset-4"><Mail className="size-4" />{email}</a></article> }
