import Link from "next/link"
import { redirect } from "next/navigation"
import { getServerSession } from "next-auth"
import { ArrowUpRight, CalendarDays, Flame, Sparkles } from "lucide-react"
import { authOptions } from "@/auth"
import { CheckInForm } from "@/components/growth/check-in-form"
import { getGrowthDashboard } from "@/lib/data/growth"

function dateLabel(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not scheduled" }

export default async function DashboardPage() {
  const session = await getServerSession(authOptions); if (!session?.user?.id) redirect("/login")
  const dashboard = await getGrowthDashboard(session.user.id); if (!dashboard?.preferences || !dashboard.primaryProject) redirect("/onboarding")
  const goal = dashboard.primaryProject
  return <div className="mx-auto w-full max-w-6xl space-y-6">
    <section className="growth-grid relative overflow-hidden rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm sm:p-9"><div className="relative z-10 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><span className="rounded-full border border-neutral-200 bg-neutral-50 px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-neutral-500">{goal.lifeArea}</span><span className="text-xs text-neutral-400">Your current intention</span></div><h1 className="mt-5 max-w-3xl text-4xl font-black leading-[1.02] tracking-[-.045em] text-neutral-950 sm:text-6xl">{goal.name}</h1><p className="mt-4 max-w-2xl text-sm font-medium leading-7 text-neutral-500">{goal.description}</p></div><Link href={`/goals/${goal.id}`} className="inline-flex w-fit items-center gap-2 rounded-full border border-neutral-200 bg-white px-4 py-2 text-xs font-bold text-neutral-800 shadow-sm transition hover:-translate-y-0.5">Explore this intention<ArrowUpRight className="size-3.5" /></Link></div><div className="relative z-10 mt-7 rounded-2xl border border-neutral-200 bg-white/90 p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-neutral-400">One next step</p><p className="mt-2 text-lg font-bold text-neutral-900">{goal.currentNextAction}</p></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><Metric icon={Flame} label="Current rhythm" value={`${dashboard.streak?.currentStreak ?? 0} reflections`} note={`Longest: ${dashboard.streak?.longestStreak ?? 0}`} /><Metric icon={CalendarDays} label="Next gentle prompt" value={dateLabel(dashboard.nextPromptAt)} note={dashboard.preferences.timezone} /><Metric icon={Sparkles} label="Patterns noticed" value={String(dashboard.activePatterns.length)} note="Only when evidence supports them" /></section>
    <section className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm sm:p-9"><CheckInForm projectId={goal.id} projectName={goal.name} currentNextAction={goal.currentNextAction} promptId={dashboard.currentPromptId} /></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black tracking-tight">Recent reflections</h2><Link href={`/goals/${goal.id}`} className="text-xs font-bold text-neutral-500 hover:text-neutral-950">See all →</Link></div>{dashboard.recentCheckIns.length ? <div className="mt-5 space-y-3">{dashboard.recentCheckIns.slice(0,3).map(item => <div key={item.id} className="rounded-2xl border border-neutral-200 bg-neutral-50/60 p-4"><div className="flex justify-between gap-4"><span className="text-[10px] font-bold uppercase tracking-wider text-neutral-500">{item.classification.replaceAll("_"," ")}</span><time className="text-[10px] font-semibold text-neutral-400">{new Date(item.createdAt).toLocaleDateString()}</time></div><p className="mt-2 line-clamp-2 text-sm leading-6 text-neutral-700">{item.response}</p></div>)}</div> : <p className="mt-4 text-sm leading-6 text-neutral-500">Your first reflection will begin the story.</p>}</div><div className="rounded-3xl border border-neutral-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black tracking-tight">What you may be learning</h2>{dashboard.activePatterns.length ? <div className="mt-5 space-y-3">{dashboard.activePatterns.slice(0,3).map(pattern => <div key={pattern.id} className="rounded-2xl border border-neutral-200 bg-neutral-50/60 p-4"><p className="text-sm leading-6 text-neutral-700">{pattern.summary}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-neutral-400">Based on {pattern.supportingCheckInIds.length} reflections</p></div>)}</div> : <p className="mt-4 text-sm leading-7 text-neutral-500">As you reflect, GrowthAI will gently surface repeated conditions, obstacles, and helpful rhythms. It will show the evidence, not make claims about who you are.</p>}</div></section>
  </div>
}

function Metric({ icon: Icon, label, value, note }: { icon: typeof Flame; label: string; value: string; note: string }) { return <div className="motion-card rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-neutral-400"><Icon className="size-4 text-neutral-900" />{label}</div><p className="mt-4 text-xl font-black leading-7 text-neutral-950">{value}</p><p className="mt-2 text-xs text-neutral-400">{note}</p></div> }
