"use client"

import { useActionState, useCallback, useMemo, useState } from "react"
import { Archive, ArrowRight, Bot, BrainCircuit, CheckCircle2, Circle, Clock3, Code2, FolderKanban, GitBranch, LockKeyhole, Map, Play, Plus, Route, Sparkles, Target } from "lucide-react"

import { createRoadmapAction, generateRoadmapAction, setRoadmapNodeStatusAction, setRoadmapStatusAction, type RoadmapActionState } from "@/app/(user)/growth-map/actions"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import type { GrowthRoadmap, GrowthRoadmapNode } from "@/lib/data/growth-map"
import { cn } from "@/lib/utils"

const typeMeta = {
  foundation: { label: "Foundation", icon: BrainCircuit, color: "text-violet-300 bg-violet-400/10" },
  core: { label: "Core skill", icon: Code2, color: "text-sky-300 bg-sky-400/10" },
  practice: { label: "Practice", icon: GitBranch, color: "text-amber-300 bg-amber-400/10" },
  project: { label: "Project", icon: FolderKanban, color: "text-emerald-300 bg-emerald-400/10" },
} as const

export function GrowthRoadmapManager({ maps, nodes }: { maps: GrowthRoadmap[]; nodes: GrowthRoadmapNode[] }) {
  const activeMaps = maps.filter((map) => map.status === "active")
  const [selectedId, setSelectedId] = useState(activeMaps[0]?.id ?? maps[0]?.id ?? "")
  const selected = maps.find((map) => map.id === selectedId) ?? activeMaps[0] ?? maps[0]
  const selectedNodes = useMemo(() => nodes.filter((node) => node.mapId === selected?.id), [nodes, selected?.id])
  const completed = selectedNodes.filter((node) => node.status === "completed").length
  const hoursDone = selectedNodes.filter((node) => node.status === "completed").reduce((sum, node) => sum + node.estimatedHours, 0)
  const totalHours = selectedNodes.reduce((sum, node) => sum + node.estimatedHours, 0)
  const progress = selectedNodes.length ? Math.round(completed / selectedNodes.length * 100) : 0
  const current = selectedNodes.find((node) => node.status === "in_progress") ?? selectedNodes.find((node) => node.status === "available")
  const stages = [...new Set(selectedNodes.map((node) => node.stage))].sort((a, b) => a - b)
  const [manualOpen, setManualOpen] = useState(false)
  const [aiOpen, setAiOpen] = useState(false)
  const [selectedNodeId, setSelectedNodeId] = useState(current?.id ?? "")
  const selectedNode = selectedNodes.find((node) => node.id === selectedNodeId) ?? current ?? selectedNodes[0]

  return <div className="growth-world relative min-h-svh overflow-hidden bg-[#03070b] text-white">
    <WorldAtmosphere />
    <div className="relative z-10 flex min-h-svh flex-col p-3 sm:p-5 lg:p-6">
      <header className="growth-hud flex flex-col gap-4 rounded-[1.4rem] border border-white/10 bg-[#071117]/75 px-4 py-3 shadow-2xl backdrop-blur-2xl sm:flex-row sm:items-center sm:justify-between sm:px-5">
        <div className="flex min-w-0 items-center gap-3"><span className="relative flex size-10 shrink-0 items-center justify-center rounded-2xl border border-primary/30 bg-primary/10 text-primary"><Route className="size-5" /><i className="absolute -right-1 -top-1 size-2.5 rounded-full bg-emerald-300 shadow-[0_0_12px_#6ee7b7]" /></span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-primary/70">Growth world</p><h1 className="truncate text-lg font-semibold tracking-tight text-white">{selected?.title ?? "Create a new world"}</h1></div></div>
        <div className="flex flex-wrap items-center gap-2"><div className="hidden items-center gap-4 rounded-full border border-white/8 bg-black/25 px-4 py-2 text-xs text-white/40 md:flex"><span><strong className="text-white">{progress}%</strong> explored</span><span className="h-3 w-px bg-white/10" /><span><strong className="text-white">{hoursDone}h</strong> mastered</span><span className="h-3 w-px bg-white/10" /><span><strong className="text-white">{stages.length}</strong> regions</span></div><Button type="button" onClick={() => setManualOpen(true)} variant="outline" className="h-9 rounded-full border-white/10 bg-white/[.04] px-4 text-xs text-white hover:bg-white/[.08]"><Plus className="size-3.5" />Create</Button><Button type="button" onClick={() => setAiOpen(true)} className="h-9 rounded-full bg-primary px-4 text-xs font-bold text-primary-foreground hover:bg-primary/85"><Sparkles className="size-3.5" />Ask AI</Button></div>
      </header>

      {selected ? <div className="mt-4 grid min-h-0 flex-1 gap-4 xl:grid-cols-[230px_minmax(0,1fr)_290px]">
        <aside className="growth-hud order-2 self-start rounded-[1.4rem] border border-white/10 bg-[#071117]/70 p-3 backdrop-blur-2xl xl:order-1"><p className="px-2 py-2 text-[10px] font-bold uppercase tracking-[.18em] text-white/30">Worlds</p><div className="space-y-1">{maps.map((map) => { const mapNodes = nodes.filter((node) => node.mapId === map.id), done = mapNodes.filter((node) => node.status === "completed").length; return <button key={map.id} type="button" onClick={() => { setSelectedId(map.id); setSelectedNodeId("") }} className={cn("group flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition", selected.id === map.id ? "bg-primary/10 text-white ring-1 ring-primary/20" : "text-white/45 hover:bg-white/[.04] hover:text-white")}><span className={cn("flex size-8 shrink-0 items-center justify-center rounded-full border", selected.id === map.id ? "border-primary/40 bg-primary/15 text-primary shadow-[0_0_18px_rgba(114,231,255,.18)]" : "border-white/10 bg-white/[.04]")}><Map className="size-3.5" /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{map.title}</span><span className="mt-0.5 block text-[9px] text-white/25">{done}/{mapNodes.length} discovered</span></span></button>})}</div><button type="button" onClick={() => setAiOpen(true)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-primary/20 py-3 text-xs font-semibold text-primary/65 hover:bg-primary/[.06] hover:text-primary"><Sparkles className="size-3.5" />Open a new world</button></aside>

        <main className="order-1 min-w-0 xl:order-2">
          <div className="relative h-[68svh] min-h-[620px] overflow-hidden rounded-[2.2rem] border border-white/10 bg-[radial-gradient(ellipse_at_50%_100%,rgba(17,94,89,.32),transparent_55%),linear-gradient(180deg,rgba(3,13,20,.35),rgba(2,9,12,.82))] shadow-[inset_0_0_100px_rgba(0,0,0,.55),0_30px_100px_rgba(0,0,0,.35)]">
            <div className="growth-world-stars absolute inset-0 opacity-70" />
            <div className="absolute inset-x-0 top-0 z-20 flex flex-col gap-3 p-5 sm:flex-row sm:items-start sm:justify-between sm:p-7"><div className="max-w-2xl"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-primary">{selected.topic}</span><span className="rounded-full border border-white/8 bg-black/25 px-3 py-1 text-[10px] capitalize text-white/35">{selected.source} forged</span></div><p className="mt-3 text-xs leading-5 text-white/40">Destination · {selected.outcome}</p></div><div className="flex items-center gap-2"><Legend color="bg-emerald-300" label="Mastered" /><Legend color="bg-primary" label="Reachable" /></div></div>
            <div className="growth-world-scroll no-scrollbar absolute inset-0 overflow-x-auto overflow-y-hidden px-[9vw] pb-16 pt-40"><div className="relative flex h-full min-w-max items-center gap-28">{stages.map((stage, stageIndex) => <WorldRegion key={stage} stage={stage} index={stageIndex} nodes={selectedNodes.filter((node) => node.stage === stage)} allNodes={selectedNodes} selectedNodeId={selectedNode?.id} onSelect={setSelectedNodeId} />)}</div></div>
            <div className="pointer-events-none absolute inset-x-0 bottom-0 h-32 bg-gradient-to-t from-[#02080b] to-transparent" />
            <div className="absolute bottom-5 left-1/2 z-20 -translate-x-1/2 rounded-full border border-white/10 bg-black/40 px-4 py-2 text-[10px] text-white/35 backdrop-blur-xl">Drag horizontally to explore the world <ArrowRight className="ml-2 inline size-3" /></div>
          </div>
        </main>

        <aside className="growth-hud order-3 self-start overflow-hidden rounded-[1.4rem] border border-white/10 bg-[#071117]/75 backdrop-blur-2xl">{selectedNode ? <NodeDetail node={selectedNode} allNodes={selectedNodes} /> : null}<div className="border-t border-white/8 p-4"><div className="flex items-center justify-between text-[10px] text-white/35"><span>World explored</span><span className="font-bold text-white">{completed}/{selectedNodes.length}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/[.07]"><div className="dynamic-progress h-full rounded-full bg-gradient-to-r from-cyan-500 to-emerald-300 shadow-[0_0_12px_rgba(114,231,255,.7)]" style={{ width: `${progress}%` }} /></div><div className="mt-4 flex items-center justify-between"><span className="text-[10px] text-white/25">~{totalHours} total hours</span><form action={setRoadmapStatusAction}><input type="hidden" name="mapId" value={selected.id} /><input type="hidden" name="status" value={selected.status === "active" ? "archived" : "active"} /><button className="inline-flex items-center gap-1.5 text-[10px] text-white/30 hover:text-white"><Archive className="size-3" />{selected.status === "active" ? "Archive world" : "Restore world"}</button></form></div></div></aside>
      </div> : <div className="relative z-10 flex flex-1 items-center justify-center py-10"><EmptyMap onManual={() => setManualOpen(true)} onAi={() => setAiOpen(true)} /></div>}
    </div>

    <ManualDialog open={manualOpen} setOpen={setManualOpen} />
    <AiDialog open={aiOpen} setOpen={setAiOpen} />
  </div>
}

function WorldAtmosphere() { return <div aria-hidden className="pointer-events-none absolute inset-0 overflow-hidden"><div className="growth-aurora growth-aurora-one absolute -left-[12%] -top-[20%] h-[65%] w-[70%] rounded-full bg-cyan-400/10 blur-[100px]" /><div className="growth-aurora growth-aurora-two absolute -right-[15%] top-[15%] h-[60%] w-[55%] rounded-full bg-violet-500/10 blur-[120px]" /><div className="growth-mist absolute inset-x-0 bottom-0 h-[55%] bg-[radial-gradient(ellipse_at_bottom,rgba(16,185,129,.13),transparent_62%)]" /><div className="growth-world-stars absolute inset-0 opacity-45" /></div> }

function WorldRegion({ stage, index, nodes, allNodes, selectedNodeId, onSelect }: { stage: number; index: number; nodes: GrowthRoadmapNode[]; allNodes: GrowthRoadmapNode[]; selectedNodeId?: string; onSelect: (id: string) => void }) {
  return <section className={cn("growth-region relative flex w-72 shrink-0 flex-col items-center", index % 2 ? "translate-y-16" : "-translate-y-8")}><div className="growth-island absolute left-1/2 top-24 h-56 w-80 -translate-x-1/2 rounded-[50%] bg-[radial-gradient(ellipse_at_50%_35%,rgba(70,180,166,.22),rgba(8,45,48,.2)_45%,transparent_72%)] blur-[1px]" /><div className="relative z-10 mb-8 text-center"><span className="text-[9px] font-bold uppercase tracking-[.25em] text-primary/45">Region {String(stage).padStart(2,"0")}</span><h2 className="mt-1 font-editorial text-2xl text-white/80">{regionName(nodes, stage)}</h2></div><div className="relative z-10 flex min-h-72 w-full flex-col items-center justify-center gap-5">{nodes.map((node, nodeIndex) => <WorldLandmark key={node.id} node={node} allNodes={allNodes} selected={selectedNodeId === node.id} offset={nodeIndex} onSelect={onSelect} />)}</div><div className="absolute -right-28 top-1/2 h-px w-32 bg-gradient-to-r from-primary/35 via-primary/15 to-transparent"><i className="growth-path-light absolute left-0 top-1/2 size-1.5 -translate-y-1/2 rounded-full bg-primary shadow-[0_0_12px_#72e7ff]" /></div></section>
}

function WorldLandmark({ node, allNodes, selected, offset, onSelect }: { node: GrowthRoadmapNode; allNodes: GrowthRoadmapNode[]; selected: boolean; offset: number; onSelect: (id: string) => void }) {
  const meta = typeMeta[node.type], Icon = meta.icon, locked = node.status === "locked"
  const parentsDone = node.parentIds.filter((id) => allNodes.find((item) => item.id === id)?.status === "completed").length
  return <button type="button" onClick={() => onSelect(node.id)} className={cn("group relative flex w-56 items-center gap-3 text-left transition duration-500", offset % 2 ? "translate-x-8" : "-translate-x-7", selected && "scale-105")}><span className={cn("growth-landmark relative flex size-14 shrink-0 items-center justify-center rounded-[45%_55%_48%_52%] border backdrop-blur-xl transition duration-500", node.status === "completed" ? "border-emerald-300/50 bg-emerald-300/15 text-emerald-200 shadow-[0_0_28px_rgba(110,231,183,.22)]" : node.status === "in_progress" ? "growth-landmark-active border-primary/60 bg-primary/20 text-primary shadow-[0_0_35px_rgba(114,231,255,.32)]" : locked ? "border-white/10 bg-white/[.035] text-white/20" : "border-primary/25 bg-[#0c252b]/75 text-primary/75 shadow-[0_0_18px_rgba(114,231,255,.1)]", selected && "ring-2 ring-white/30 ring-offset-4 ring-offset-transparent")}><Icon className="size-5" />{locked ? <LockKeyhole className="absolute -bottom-1 -right-1 size-4 rounded-full bg-[#081116] p-0.5 text-white/30" /> : null}</span><span className="min-w-0"><span className={cn("block text-xs font-semibold leading-5", locked ? "text-white/25" : "text-white/75 group-hover:text-white")}>{node.title}</span><span className="mt-0.5 block text-[9px] text-white/25">{locked ? `${parentsDone}/${node.parentIds.length} paths opened` : node.status.replace("_", " ")}</span></span></button>
}

function NodeDetail({ node, allNodes }: { node: GrowthRoadmapNode; allNodes: GrowthRoadmapNode[] }) {
  const meta = typeMeta[node.type], Icon = meta.icon, prerequisites = node.parentIds.map((id) => allNodes.find((item) => item.id === id)?.title).filter(Boolean), locked = node.status === "locked"
  return <div className="p-5"><div className="flex items-center justify-between"><span className={cn("flex size-10 items-center justify-center rounded-2xl", meta.color)}><Icon className="size-5" /></span><span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-wide", node.status === "completed" ? "bg-emerald-400/10 text-emerald-300" : node.status === "in_progress" ? "bg-primary/10 text-primary" : "bg-white/[.05] text-white/30")}>{locked ? <LockKeyhole className="size-3" /> : <Circle className="size-2.5" />}{node.status.replace("_", " ")}</span></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[.16em] text-primary/55">{meta.label} · Region {node.stage}</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-white">{node.title}</h2><p className="mt-3 text-xs leading-6 text-white/40">{node.description}</p><div className="mt-5 flex items-center gap-2 rounded-xl border border-white/8 bg-black/20 px-3 py-2.5 text-xs text-white/35"><Clock3 className="size-3.5 text-primary/60" />Estimated journey · <strong className="text-white/65">{node.estimatedHours} hours</strong></div>{prerequisites.length ? <div className="mt-4"><p className="text-[9px] font-bold uppercase tracking-wide text-white/25">Paths required</p><div className="mt-2 space-y-1.5">{prerequisites.map((title) => <p key={title} className="flex items-center gap-2 text-[10px] text-white/35"><GitBranch className="size-3 text-primary/40" />{title}</p>)}</div></div> : null}{!locked ? <form action={setRoadmapNodeStatusAction} className="mt-5"><input type="hidden" name="nodeId" value={node.id} /><input type="hidden" name="status" value={node.status === "completed" ? "available" : node.status === "in_progress" ? "completed" : "in_progress"} /><button className={cn("flex h-11 w-full items-center justify-center gap-2 rounded-xl text-xs font-bold transition", node.status === "completed" ? "border border-white/10 text-white/40 hover:bg-white/[.05] hover:text-white" : node.status === "in_progress" ? "bg-emerald-300 text-emerald-950 shadow-[0_0_24px_rgba(110,231,183,.14)]" : "bg-primary text-primary-foreground shadow-[0_0_24px_rgba(114,231,255,.15)]")} >{node.status === "completed" ? "Reopen landmark" : node.status === "in_progress" ? <><CheckCircle2 className="size-4" />Claim mastery</> : <><Play className="size-3.5" />Begin journey</>}</button></form> : <p className="mt-5 rounded-xl border border-white/8 bg-white/[.025] p-3 text-center text-[10px] leading-5 text-white/25">Complete the connected landmarks to reveal this path.</p>}</div>
}

function regionName(nodes: GrowthRoadmapNode[], stage: number) { const type = nodes[0]?.type; return type === "foundation" ? "The Origin" : type === "practice" ? "The Trials" : type === "project" ? "The Forge" : stage === 1 ? "The Beginning" : "The Frontier" }

function ManualDialog({ open, setOpen }: { open: boolean; setOpen: (open: boolean) => void }) {
  const submit = useCallback(async (previous: RoadmapActionState, data: FormData) => { const next = await createRoadmapAction(previous, data); if (next.updatedAt) setOpen(false); return next }, [setOpen])
  const [state, action, pending] = useActionState(submit, {})
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto border-white/[.12] bg-[#171717] p-0 text-white sm:max-w-2xl"><DialogHeader className="border-b border-white/[.08] px-6 py-5"><DialogTitle className="text-xl font-semibold">Build a roadmap manually</DialogTitle><DialogDescription className="text-sm text-white/40">Add milestones in learning order. Each milestone will unlock after the previous one is completed.</DialogDescription></DialogHeader><form action={action} className="space-y-5 px-6 pb-6"><div className="grid gap-4 sm:grid-cols-2"><Field label="Roadmap name" htmlFor="manual-title"><Input id="manual-title" name="title" placeholder="Full-stack Web Developer" required minLength={3} maxLength={80} className="h-11 border-white/10 bg-white/[.05] text-white" /></Field><Field label="Topic" htmlFor="manual-topic"><Input id="manual-topic" name="topic" placeholder="Web Development" required minLength={2} maxLength={80} className="h-11 border-white/10 bg-white/[.05] text-white" /></Field></div><Field label="Target outcome" htmlFor="manual-outcome"><Textarea id="manual-outcome" name="outcome" placeholder="Build and deploy production-ready full-stack applications independently." required minLength={5} maxLength={300} className="min-h-20 border-white/10 bg-white/[.05] text-white" /></Field><Field label="Milestones, one per line" htmlFor="manual-milestones"><Textarea id="manual-milestones" name="milestones" placeholder={"HTML and semantic accessibility\nCSS layouts and responsive design\nJavaScript fundamentals\nReact applications\nBackend APIs and databases\nDeploy a full-stack capstone"} required className="min-h-44 border-white/10 bg-white/[.05] font-mono text-xs leading-6 text-white" /></Field>{state.error ? <p className="rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{state.error}</p> : null}<DialogButtons pending={pending} label="Create roadmap" onCancel={() => setOpen(false)} /></form></DialogContent></Dialog>
}

function AiDialog({ open, setOpen }: { open: boolean; setOpen: (open: boolean) => void }) {
  const submit = useCallback(async (previous: RoadmapActionState, data: FormData) => { const next = await generateRoadmapAction(previous, data); if (next.updatedAt) setOpen(false); return next }, [setOpen])
  const [state, action, pending] = useActionState(submit, {})
  return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto border-white/[.12] bg-[#171717] p-0 text-white sm:max-w-2xl"><DialogHeader className="border-b border-white/[.08] px-6 py-5"><DialogTitle className="flex items-center gap-2 text-xl font-semibold"><Bot className="size-5 text-primary" />Generate a complete map</DialogTitle><DialogDescription className="text-sm text-white/40">GrowthAI will create foundations, core skills, practice loops, projects, and prerequisites.</DialogDescription></DialogHeader><form action={action} className="space-y-5 px-6 pb-6"><Field label="What do you want to learn?" htmlFor="ai-topic"><Input id="ai-topic" name="topic" placeholder="Data Structures and Algorithms" required minLength={2} maxLength={80} className="h-11 border-white/10 bg-white/[.05] text-white" /></Field><Field label="What should you be able to do?" htmlFor="ai-outcome"><Textarea id="ai-outcome" name="outcome" placeholder="Solve medium interview problems independently and explain time and space complexity." required minLength={5} maxLength={300} className="min-h-24 border-white/10 bg-white/[.05] text-white" /></Field><Field label="Current experience" htmlFor="ai-experience"><Textarea id="ai-experience" name="experience" placeholder="I know basic JavaScript but have not studied algorithms formally." maxLength={500} className="min-h-20 border-white/10 bg-white/[.05] text-white" /></Field><div className="rounded-xl border border-primary/15 bg-primary/[.05] p-3 text-xs leading-5 text-white/40"><Sparkles className="mr-2 inline size-3.5 text-primary" />The generated map remains editable through milestone progress. AI can make mistakes—review the sequence before relying on it.</div>{state.error ? <p className="rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{state.error}</p> : null}<DialogButtons pending={pending} label="Generate roadmap" pendingLabel="Designing your map…" onCancel={() => setOpen(false)} /></form></DialogContent></Dialog>
}

function EmptyMap({ onManual, onAi }: { onManual: () => void; onAi: () => void }) { return <section className="overflow-hidden rounded-[2rem] border border-white/[.09] bg-[#111]"><div className="grid lg:grid-cols-[1.05fr_.95fr]"><div className="p-7 sm:p-10"><span className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Map className="size-6" /></span><h2 className="mt-6 text-3xl font-semibold tracking-[-.035em] text-white">Create your first complete growth map.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-white/45">Start with a skill and a visible outcome. The map will show what to learn, what depends on what, and where to prove the skill with practice and projects.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={onAi} className="h-11 rounded-full bg-primary px-6 font-bold text-primary-foreground"><Sparkles className="size-4" />Generate with AI</Button><Button onClick={onManual} variant="outline" className="h-11 rounded-full border-white/10 bg-white/[.04] px-6 text-white hover:bg-white/[.08]"><Plus className="size-4" />Build manually</Button></div></div><div className="border-t border-white/[.07] bg-white/[.02] p-6 lg:border-l lg:border-t-0 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/30">A useful map contains</p><div className="mt-4 space-y-3">{[[BrainCircuit,"Foundations","The concepts everything else depends on"],[GitBranch,"Prerequisites","A clear order instead of a random checklist"],[FolderKanban,"Proof projects","Outputs that demonstrate real capability"],[Target,"Visible progress","One current milestone and an honest completion rate"]].map(([Icon,title,text]) => { const ItemIcon = Icon as typeof BrainCircuit; return <div key={String(title)} className="flex gap-3 rounded-2xl border border-white/[.07] bg-black/20 p-4"><span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-white/[.05] text-primary"><ItemIcon className="size-4" /></span><div><p className="text-sm font-semibold text-white">{String(title)}</p><p className="mt-1 text-xs text-white/35">{String(text)}</p></div></div>})}</div></div></div></section> }
function Legend({ color, label }: { color: string; label: string }) { return <span className="inline-flex items-center gap-1.5"><i className={cn("size-1.5 rounded-full", color)} />{label}</span> }
function Field({ label, htmlFor, children }: { label: string; htmlFor: string; children: React.ReactNode }) { return <div className="space-y-2"><Label htmlFor={htmlFor} className="text-xs font-semibold text-white/65">{label}</Label>{children}</div> }
function DialogButtons({ pending, label, pendingLabel = "Creating…", onCancel }: { pending: boolean; label: string; pendingLabel?: string; onCancel: () => void }) { return <div className="flex flex-col-reverse gap-2 border-t border-white/[.08] pt-5 sm:flex-row sm:justify-end"><Button type="button" variant="ghost" onClick={onCancel} className="h-11 rounded-xl px-5 text-white/55 hover:bg-white/[.06] hover:text-white">Cancel</Button><Button disabled={pending} className="h-11 rounded-xl bg-primary px-6 font-bold text-primary-foreground hover:bg-primary/85">{pending ? pendingLabel : label}<ArrowRight className="size-4" /></Button></div> }
