import { notFound, redirect } from "next/navigation"
import { getServerSession } from "next-auth"
import { authOptions } from "@/auth"
import { checkInFeedbackAction, generateWeeklyReviewAction, setPatternStatusAction, updateProjectStatusAction } from "@/app/(user)/growth-actions"
import { CheckInForm } from "@/components/growth/check-in-form"
import { Button } from "@/components/ui/button"
import { getProjectWorkspace } from "@/lib/data/growth"

export default async function ProjectPage({ params }: { params: Promise<{ projectId: string }> }) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.id) redirect("/login")
  const { projectId } = await params
  const workspace = await getProjectWorkspace(session.user.id, projectId)
  if (!workspace) notFound()
  const { project } = workspace
  return <div className="mx-auto w-full max-w-6xl space-y-6">
    <section className="rounded-3xl border border-white/10 bg-[#2b2b2b] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-emerald-400">{project.status} commitment</p><h1 className="mt-3 text-4xl font-semibold text-white">{project.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">{project.description}</p></div><form action={updateProjectStatusAction} className="flex gap-2"><input type="hidden" name="projectId" value={project.id} />{project.status === "active" ? <><Button name="status" value="paused" variant="outline" className="rounded-full border-white/15">Pause</Button><Button name="status" value="shipped" className="rounded-full bg-emerald-400 text-zinc-950 hover:bg-emerald-300">Mark shipped</Button></> : <Button name="status" value="active" className="rounded-full">Reactivate</Button>}</form></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info label="Ship date" value={project.targetShipDate} /><Info label="Finish line" value={project.definitionOfShipped} /><Info label="Streak" value={`${workspace.streak?.currentStreak ?? 0} check-ins`} /></div></section>
    {project.status === "active" ? <section className="rounded-3xl border border-white/10 bg-[#2b2b2b] p-6 sm:p-8"><CheckInForm projectId={project.id} projectName={project.name} currentNextAction={project.currentNextAction} promptId={workspace.currentPromptId} /></section> : null}
    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-3"><h2 className="text-xl font-semibold text-white">Check-in history</h2>{workspace.checkIns.length ? workspace.checkIns.map(item => <article key={item.id} className="rounded-2xl border border-white/10 bg-[#2b2b2b] p-5"><div className="flex justify-between gap-3"><span className="text-xs uppercase tracking-wide text-emerald-400">{item.classification.replaceAll("_", " ")}</span><time className="text-xs text-zinc-600">{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-3 text-sm leading-6 text-zinc-200">{item.response}</p><div className="mt-4 rounded-xl bg-zinc-950/40 p-4"><p className="text-sm leading-6 text-zinc-300">{item.aiResponse}</p><p className="mt-2 text-sm font-medium text-white">{item.followUpQuestion}</p></div><p className="mt-3 text-xs text-zinc-500">Committed next: {item.nextAction}</p>{item.helpful === null ? <form action={checkInFeedbackAction} className="mt-3 flex gap-2"><input type="hidden" name="checkInId" value={item.id} /><input type="hidden" name="projectId" value={project.id} /><button name="helpful" value="true" className="text-xs text-zinc-500 hover:text-emerald-400">Helpful</button><button name="helpful" value="false" className="text-xs text-zinc-500 hover:text-red-300">Not useful</button></form> : null}</article>) : <p className="rounded-2xl border border-white/10 bg-[#2b2b2b] p-5 text-sm text-zinc-500">No check-ins yet.</p>}</div><aside className="space-y-4"><div className="rounded-2xl border border-white/10 bg-[#2b2b2b] p-5"><h2 className="font-semibold text-white">Observed patterns</h2>{workspace.patterns.length ? <div className="mt-3 space-y-3">{workspace.patterns.map(pattern => <div key={pattern.id} className="rounded-xl border border-white/10 p-3"><p className="text-sm leading-6 text-zinc-300">{pattern.summary}</p>{pattern.status === "active" ? <form action={setPatternStatusAction} className="mt-2 flex gap-3"><input type="hidden" name="patternId" value={pattern.id} /><input type="hidden" name="projectId" value={project.id} /><button name="status" value="acknowledged" className="text-xs text-emerald-400">Acknowledge</button><button name="status" value="dismissed" className="text-xs text-zinc-500">Dismiss</button></form> : <p className="mt-2 text-xs capitalize text-zinc-600">{pattern.status}</p>}</div>)}</div> : <p className="mt-3 text-sm text-zinc-500">Not enough history yet.</p>}</div><form action={generateWeeklyReviewAction} className="rounded-2xl border border-white/10 bg-[#2b2b2b] p-5"><input type="hidden" name="projectId" value={project.id} /><h2 className="font-semibold text-white">Weekly reflection</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Generate an editable, evidence-based summary from this week.</p><Button className="mt-4 rounded-full" type="submit">Generate review</Button></form></aside></section>
  </div>
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 p-4"><p className="text-xs uppercase tracking-wide text-zinc-600">{label}</p><p className="mt-2 text-sm leading-6 text-zinc-200">{value}</p></div> }
