import Link from "next/link"
import { notFound } from "next/navigation"
import { ArrowUpRight, Leaf } from "lucide-react"
import { getPublicProject } from "@/lib/data/growth"

export default async function PublicGrowthPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const data = await getPublicProject(slug); if (!data) notFound()
  return <main className="growth-grid min-h-screen bg-[#fafafa] px-5 py-8 text-neutral-950"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between"><Link href="/" className="font-display text-sm tracking-wide">GrowthAI</Link><Link href="/signup" className="rounded-full bg-neutral-950 px-4 py-2 text-xs font-bold text-white">Begin your own</Link></header><section className="mt-16 rounded-3xl border border-neutral-200 bg-white p-7 shadow-sm sm:p-11"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-neutral-400"><Leaf className="size-4 text-neutral-900" />A growth intention shared by choice</div><h1 className="mt-6 text-4xl font-black leading-[1.02] tracking-[-.045em] sm:text-6xl">{data.project.name}</h1><p className="mt-5 text-base font-medium leading-8 text-neutral-500">{data.project.description}</p><div className="mt-9 grid gap-3 sm:grid-cols-2"><Stat label="What progress means" value={data.project.definitionOfShipped} /><Stat label="Reflection date" value={data.project.targetShipDate} /><Stat label="Reflections completed" value={String(data.checkInCount)} /><Stat label="Meaningful steps noticed" value={String(data.meaningfulProgressCount)} />{data.streak ? <Stat label="Current reflection rhythm" value={String(data.streak.currentStreak)} /> : null}<Stat label="Status" value={data.project.status} /></div></section><p className="mx-auto mt-6 max-w-xl text-center text-xs leading-6 text-neutral-400">Only this limited view is public. Raw reflections, private reasons, patterns, evidence, and coaching remain private.</p><div className="mt-8 text-center"><Link href="/signup" className="inline-flex items-center gap-2 rounded-full bg-neutral-950 px-6 py-3 text-sm font-bold text-white">Choose what matters to you<ArrowUpRight className="size-4" /></Link></div></div></main>
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-neutral-200 bg-neutral-50/60 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-neutral-400">{label}</p><p className="mt-2 text-sm font-semibold leading-6 text-neutral-700 capitalize">{value}</p></div> }
