import { BarChart3, Clock3, Coins, Repeat2, ShieldAlert, Target } from "lucide-react"
import { requireAdminPageRole } from "@/lib/admin/page-auth"
import { getAdminProductAnalytics } from "@/lib/data/admin"

export const metadata = { title: "Product analytics" }
export default async function AdminAnalyticsPage() {
  await requireAdminPageRole("support-read", "owner")
  const data = await getAdminProductAnalytics(28)
  const activationRate = data.activeUsers ? data.activatedUsers / data.activeUsers : 0
  const taskAcceptance = data.counts.plan_proposed ? data.counts.task_accepted / data.counts.plan_proposed : 0
  return <div className="space-y-7"><section><p className="text-[10px] font-bold uppercase tracking-[.18em] text-primary">Core loop v1 · last {data.days} days</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Product analytics</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-500">Content-free events only: no message text, goal titles, or task titles leave the product database.</p></section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Target} label="Activation" value={percent(activationRate)} note={`${data.activatedUsers}/${data.activeUsers} active users accepted a task`} /><Metric icon={Repeat2} label="Day-1 return" value={String(data.day1Retained)} note="Activated users with a later event" /><Metric icon={Repeat2} label="Day-7 return" value={String(data.day7Retained)} note="Activity 7+ days after first event" /><Metric icon={Repeat2} label="Week-4 return" value={String(data.week4Retained)} note={`${data.paidRetained} retained paid users`} /><Metric icon={Clock3} label="Response p95" value={`${Math.round(data.p95LatencyMs / 100) / 10}s`} note={`${data.fallbackResponses} fallback responses`} /><Metric icon={Coins} label="Cost / active" value={`$${data.costPerActiveUserUsd.toFixed(3)}`} note={`$${data.totalCostUsd.toFixed(2)} tracked model cost`} /><Metric icon={BarChart3} label="Review return" value={String(data.weeklyReportUsers)} note="Unique report viewers" /><Metric icon={ShieldAlert} label="Safety" value={String(data.safetyInterventions)} note="Deterministic interventions" /></section><section className="rounded-2xl border border-white/8 bg-white/[.025] p-5 sm:p-6"><h2 className="text-sm font-bold text-white">Funnel events</h2><p className="mt-1 text-xs text-neutral-600">Activation = meaningful conversation followed by at least one accepted task.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.counts).map(([name, count]) => <article key={name} className="rounded-xl border border-white/7 bg-black/10 p-4"><p className="text-xl font-semibold text-white">{count}</p><p className="mt-1 text-[10px] capitalize text-neutral-500">{name.replaceAll("_", " ")}</p></article>)}</div><p className="mt-5 text-xs text-neutral-500">Proposal acceptance: {percent(taskAcceptance)}. Validate event counts against task, message, report, and subscription source records before making launch decisions.</p></section><section className="flex gap-3 rounded-2xl border border-amber-500/15 bg-amber-500/5 p-4"><BarChart3 className="mt-0.5 size-4 shrink-0 text-amber-400" /><p className="text-xs leading-5 text-amber-100/60">These figures describe observed product actions, not wellbeing or user worth. Small cohorts should not be treated as statistically reliable.</p></section></div>
}
function percent(value: number) { return `${Math.round(value * 100)}%` }
function Metric({ icon: Icon, label, value, note }: { icon: typeof Target; label: string; value: string; note: string }) { return <article className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><Icon className="size-4 text-primary" /><p className="mt-5 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs font-semibold text-neutral-300">{label}</p><p className="mt-2 text-[10px] leading-4 text-neutral-600">{note}</p></article> }
